### ISSUE TITLE
Ошибка в graph.py

### ISSUE THREAD

**Issue by murych** [stleon/vk_friends#15]
После прохождения всего цикла настроек, успешного запуска `call.py` и даже генерации файла `deep_friends_dict`, вызов `graph.py` обваливается со следующим выводом:

``` python
C:/Python34/python.exe C:/dist/git/vk_friends/graph.py
Количество вершин: 6789
Количество ребер: 7214
Связный граф? True
Диамерт графа: 4
Центр графа: [*******]
Радиус графа: 2
Page Rank: [(*******, 0.0779041810326803), (*******, 0.054450532986464246), (*******, 0.04823900755756001), (*******, 0.04170485634521999), (*******, 0.035951607931525256)]
Коэффициент кластеризации 0.026503162618954218
Traceback (most recent call last):
  File "C:/dist/git/vk_friends/graph.py", line 45, in <module>
    deep_friends.draw_graph()
  File "C:/dist/git/vk_friends/graph.py", line 29, in draw_graph
    plt.savefig("%s graph.png" % datetime.now().strftime('%H:%M:%S %d-%m-%Y'))
  File "C:\Python34\lib\site-packages\matplotlib\pyplot.py", line 688, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\Python34\lib\site-packages\matplotlib\figure.py", line 1539, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "C:\Python34\lib\site-packages\matplotlib\backend_bases.py", line 2230, in print_figure
    **kwargs)
  File "C:\Python34\lib\site-packages\matplotlib\backends\backend_agg.py", line 532, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
OSError: [Errno 22] Invalid argument: '22:29:05 30-11-2015 graph.png'

Process finished with exit code 1
```

(ID замазал звездочками, значения возвращаются реальные).
Насколько я понял, проблема в параметрах функции `plt.savefig`, т.к. при использовании простого

``` python
plt.savefig("graph.png")
```

после долгих раздумий сработала.

**Comment by stleon** [comment]
@murych  спасибо за сообщение. 

У меня на маке все работает, поэтому склонен считать, что в названии файла есть недопустимые символы для винды. 

Файлы было бы хорошо называть по **unix timestamp**, например, `1448918823.png`. 

Если есть время и желание, то жду от тебя pull request)
